
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: andersen0505!!
    url: jdbc:mariadb://localhost:3306/db_ebricks?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8
    username: ebricks

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  mvc:
    static-path-pattern: /static/**
    resources:
      add-mappings: true
      static-locations: classpath:/static/

  jpa:
    #open-in-view: false #https://kihoonkim.github.io/2017/01/27/JPA%28Java%20ORM%29/1.%20JPA-%ED%99%98%EA%B2%BD%20%EC%84%A4%EC%A0%95/
    generate-ddl: true
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ddl-auto: update
        ##schema_update:
        ##unique_constraint_strategy: RECREATE_QUIETLY #https://discourse.hibernate.org/t/hbm2ddl-auto-update-recreating-existing-indexes-after-drop/3991
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
logging:
  level:
    me.silvernine: DEBUG

jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400